# Generated by Django 3.2.7 on 2021-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50, unique=True)),
                ('caticonnm', models.CharField(max_length=100)),
            ],
        ),
    ]
