# Generated by Django 3.2.7 on 2021-10-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('subcatnm', models.CharField(max_length=50, unique=True)),
                ('subcaticonnm', models.CharField(max_length=100)),
            ],
        ),
    ]
