# Generated by Django 3.2.9 on 2021-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
